openapi: 3.1.0
info:
  title: AI Kanban Board API
  version: 1.0.0
  description: API documentation for the AI-powered Kanban Board
servers:
  - url: "http://localhost:5050/api/v1"
    description: Development Server
tags:
  - name: Auth
    description: Authentication operations
  - name: Board
    description: Board operations
components:
  schemas:
    Success:
      $ref: './schemas.yaml#/components/schemas/Success'
    Error:
      $ref: './schemas.yaml#/components/schemas/Error'
    AddMemberRequest:
      $ref: './schemas.yaml#/components/schemas/RegisterRequest'
    BoardCreateRequest:
      $ref: './schemas.yaml#/components/schemas/BoardCreateRequest'
    BoardsListResponse:
      $ref: './schemas.yaml#/components/schemas/BoardsListResponse'
    BoardUpdateRequest:
      $ref: './schemas.yaml#/components/schemas/BoardUpdateRequest'
    DetailBoardResponse:
      $ref: './schemas.yaml#/components/schemas/DetailBoardResponse'
    LoginRequest:
      $ref: './schemas.yaml#/components/schemas/LoginRequest'
    RegisterRequest:
      $ref: './schemas.yaml#/components/schemas/RegisterRequest'
    UserProfileResponse:
      $ref: './schemas.yaml#/components/schemas/UserProfileResponse'
  responses:
    ErrorResponse:
      $ref: './responses.yaml#/components/responses/ErrorResponse'
    AddMemberSuccessResponse:
      $ref: './responses.yaml#/components/responses/AddMemberSuccessResponse'
    BoardCreateSuccessResponse:
      $ref: './responses.yaml#/components/responses/BoardCreateSuccessResponse'
    BoardUpdateSuccessResponse:
      $ref: './responses.yaml#/components/responses/BoardUpdateSuccessResponse'
    UserLoginSuccessResponse:
      $ref: './responses.yaml#/components/responses/UserLoginSuccessResponse'
    UserRegisterSuccessResponse:
      $ref: './responses.yaml#/components/responses/UserRegisterSuccessResponse'
    ValidationErrorResponse:
      $ref: './responses.yaml#/components/responses/ValidationErrorResponse'
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
paths:
  /auth/register:
    $ref: './auth/register.yaml#/paths/~1auth~1register'
  /auth/login:
    $ref: './auth/login.yaml#/paths/~1auth~1login'
  /auth/me:
    $ref: './auth/me.yaml#/paths/~1auth~1me'
  
  /boards:
    $ref: './board/boards.yaml#/paths/~1boards'
  /boards/{board_id}:
    $ref: './board/board-by-id.yaml#/paths/~1boards~1{board_id}'
  /boards/{board_id}/members:
    $ref: './board/board-by-id.yaml#/paths/~1boards~1{board_id}~1members'
  