openapi: 3.1.0
info:
  title: Components Fragment Schemas
  version: 1.0.0
paths: {}

components:
  schemas:
    AddMemberRequest:
      title: Add member Request
      type: object
      required:
        - email
      properties:
        email:
          type: string
          format: email
        role:
          type: string
          enum:
            - admin
            - member
    Success:
      type: object
      properties:
        status:
          type: string
          example: OK
        message:
          type: string
          example: Success
        data:
          type: object
    Error:
      type: object
      properties:
        status:
          type: string
          example: ERROR | FAILED
        message:
          type: string
        errors:
          anyOf:
            - type: array
              format: any
            - type: object
              format: any
            - type: "null"
            - type: string
    BoardCreateRequest:
      title: Board Create Request
      type: object
      required:
        - title
      properties:
        title:
          type: string
        description:
          oneOf:
            - type: string
            - type: "null"
        color:
          oneOf:
            - type: string
            - type: "null"
    BoardsListResponse:
      title: Boards List Response
      type: object
      allOf:
        - $ref: '#/components/schemas/Success'
        - type: object
          properties:
            data:
              type: object
              properties:
                boards:
                  type: array
                  items:
                    type: object
                    properties:
                      is_owner:
                        type: boolean
                      task_count:
                        type: number
                      member_count:
                        type: number
                      created_at:
                        type: string
                        format: date-time
                      updated_at:
                        type: string
                        format: date-time
                      id:
                        type: string
                        format: uuid
                      title:
                        type: string
                      description:
                        oneOf:
                          - type: string
                          - type: "null"
                      color:
                        oneOf:
                          - type: string
                          - type: "null"
                      owner_id:
                        type: string
                        format: uuid
    BoardUpdateRequest:
      title: Board Update Request
      type: object
      properties:
        title:
          oneOf:
            - type: string
            - type: "null"
        description:
          oneOf:
            - type: string
            - type: "null"
        color:
          oneOf:
            - type: string
            - type: "null"
    DetailBoardResponse:
      title: Detail Board Response
      type: object
      allOf:
        - $ref: '#/components/schemas/Success'
        - type: object
          properties:
            data:
              type: object
              properties:
                board:
                  type: object
                  properties:
                    created_at:
                      type: string
                      format: date-time
                    updated_at:
                      type: string
                      format: date-time
                    id:
                      type: string
                      format: uuid
                    title:
                      type: string
                    description:
                      oneOf:
                        - type: string
                        - type: "null"
                    color:
                      oneOf:
                        - type: string
                        - type: "null"
                    owner_id:
                      type: string
                      format: uuid
                columns:
                  type: array
                  items:
                    type: object
                    properties:
                      created_at:
                        type: string
                        format: date-time
                      updated_at:
                        type: string
                        format: date-time
                      id:
                        type: string
                        format: uuid
                      board_id:
                        type: string
                        format: uuid
                      title:
                        type: string
                      position:
                        type: number
                tasks:
                  type: array
                  items:
                    type: object
                    properties:
                      assignee_name:
                        oneOf:
                          - type: string
                          - type: "null"
                      assignee_email:
                        oneOf:
                          - type: string
                          - type: "null"
                      assignee_avatar:
                        oneOf:
                          - type: string
                          - type: "null"
                      created_at:
                        type: string
                        format: date-time
                      updated_at:
                        type: string
                        format: date-time
                      id:
                        type: string
                        format: uuid
                      board_id:
                        type: string
                        format: uuid
                      column_id:
                        type: string
                        format: uuid
                      title:
                        type: string
                      description:
                        oneOf:
                          - type: string
                          - type: "null"
                      priority:
                        type: string
                        enum:
                          - low
                          - medium
                          - high
                          - urgent
                          - null
                      due_date:
                        oneOf:
                          - type: string
                            format: date-time
                          - type: "null"
                      assignee_id:
                        oneOf:
                          - type: string
                            format: uuid
                          - type: "null"
                      position:
                        type: number
                      created_by:
                        oneOf:
                          - type: string
                            format: uuid
                          - type: "null"
                members:
                  type: array
                  items:
                    type: object
                    properties:
                      id:
                        type: string
                        format: uuid
                      name:
                        type: string
                      email:
                        type: string
                        format: email
                      avatar_url:
                        oneOf:
                          - type: string
                          - type: "null"
                      role:
                        type: string
                        enum:
                          - admin
                          - owner
                          - member
                      joined_at:
                        type: string
                        format: date-time
                role:
                  type: string
                  enum:
                    - admin
                    - owner
                    - member
    LoginRequest:
      title: Login Request
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
        password:
          type: string
    RegisterRequest:
      title: Register Request
      type: object
      required:
        - name
        - email
        - password
        - confirm_password
      properties:
        name:
          type: string
        email:
          type: string
          format: email
        password:
          type: string
        confirm_password:
          type: string
    UserProfileResponse:
      title: User Profile Response
      type: object
      allOf:
        - $ref: '#/components/schemas/Success'
        - type: object
          properties:
            data:
              type: object
              properties:
                id:
                  type: string
                  format: uuid
                name:
                  type: string
                email:
                  type: string
                  format: email
                avatar_url:
                  oneOf:
                    - type: string
                    - type: "null"
                created_at:
                  type: string
                  format: date-time
                  oneOf:
                    - type: string
                    - type: "null"
