openapi: 3.1.0
info:
  title: Endpoint Detail Board
  version: 1.0.0
paths:
  /boards/{board_id}:
    get:
      summary: Get a board by ID
      tags: [Board]
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: board_id
          required: true
          schema:
            type: string
          description: The board ID
      responses:
        '200':
          description: Get board details successfully
          content:
            application/json:
              schema:
                $ref: '../schemas.yaml#/components/schemas/DetailBoardResponse'
        '400':
          description: Get board details bad request
          $ref: '../responses.yaml#/components/responses/ErrorResponse'
        '401':
          description: Unauthorized
          $ref: '../responses.yaml#/components/responses/ErrorResponse'
        '403':
          description: Forbidden (No access to this board)
          $ref: '../responses.yaml#/components/responses/ErrorResponse'
        '404':
          description: Board not found
          $ref: '../responses.yaml#/components/responses/ErrorResponse'
        '500':
          description: Internal server error
          $ref: '../responses.yaml#/components/responses/ErrorResponse'
    patch:
      summary: Update a board
      tags: [Board]
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: board_id
          required: true
          schema:
            type: string
          description: The board ID
      requestBody:
        content:
          application/json:
            schema:
              $ref: '../schemas.yaml#/components/schemas/BoardUpdateRequest'
      responses:
        '200':
          description: Board updated successfully
          $ref: "../responses.yaml#/components/responses/BoardUpdateSuccessResponse"
        '401':
          description: Unauthorized
          $ref: '../responses.yaml#/components/responses/ErrorResponse'
        '422':
          description: Board update validation error
          $ref: '../responses.yaml#/components/responses/ValidationErrorResponse'
        '403':
          description: Forbidden (No access to this board)
          $ref: '../responses.yaml#/components/responses/ErrorResponse'
        '404':
          description: Board not found
          $ref: '../responses.yaml#/components/responses/ErrorResponse'
        '500':
          description: Internal server error
          $ref: '../responses.yaml#/components/responses/ErrorResponse'
    delete:
      summary: Delete a board
      tags: [Board]
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: board_id
          required: true
          schema:
            type: string
          description: The board ID
      responses:
        '200':
          description: Delete board successfully
          content:
            application/json:
              schema:
                properties:
                  id:
                    type: string
        '400':
          description: Delete board bad request
          $ref: '../responses.yaml#/components/responses/ErrorResponse'
        '401':
          description: Unauthorized
          $ref: '../responses.yaml#/components/responses/ErrorResponse'
        '403':
          description: Forbidden (No access to this board)
          $ref: '../responses.yaml#/components/responses/ErrorResponse'
        '404':
          description: Board not found
          $ref: '../responses.yaml#/components/responses/ErrorResponse'
        '500':
          description: Internal server error
          $ref: '../responses.yaml#/components/responses/ErrorResponse'
