openapi: 3.1.0
info:
  title: Endpoint Login
  version: 1.0.0
paths:
  /auth/me:
    get:
      summary: Get current authenticated user
      tags: [Auth]
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Get user profile successful
          content:
            application/json:
              schema:
                $ref: '../schemas.yaml#/components/schemas/UserProfileResponse'
        '401':
          description: Unauthorized
          $ref: '../responses.yaml#/components/responses/ErrorResponse'
        '404':
          description: Data not found
          $ref: '../responses.yaml#/components/responses/ErrorResponse'
        '500':
          description: Internal server error
          $ref: '../responses.yaml#/components/responses/ErrorResponse'
