openapi: 3.0.0
info:
  title: Endpoint Register
  version: 1.0.0
paths:
  /auth/register:
    post:
      summary: Register a new user
      tags: [Auth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
                confirm_password:
                  type: string
      responses:
        '201':
          description: User successfully registered
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '../schemas.yaml#/components/schemas/BaseResponse'
                  - type: object
                    properties:
                      data:
                        type: object
                        properties:
                          id:
                            type: string
                            format: uuid
                          email:
                            type: string
        '400':
          description: Validation error
          content:
            application/json:
              schema:
                $ref: '../schemas.yaml#/components/schemas/ErrorResponse'
